### ISSUE TITLE
项目搭建

### ISSUE THREAD

**Issue by peppa-xyz** [Wuxinyue1999/wxy-rpc#3]
你好，我想问下，这个项目最初的版本是在哪里，我想从头开始搭建这个项目，但是不知道去哪里找到最初的项目版本，或者这个有原始的博客或视频教程吗

**Comment by viego1999** [comment]
我是先在B站找了个简易rpc教程（图灵的），然后自己再把每一块内容结合其他的rpc框架（dubbo和其他人开源的）的原理进行完善



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月5日(周日) 晚上11:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [viego1999/wxy-rpc] 项目搭建 (Issue #3)




 
你好，我想问下，这个项目最初的版本是在哪里，我想从头开始搭建这个项目，但是不知道去哪里找到最初的项目版本，或者这个有原始的博客或视频教程吗

**Comment by peppa-xyz** [comment]
好的，感谢
